<?php

use Illuminate\Database\Seeder;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $positions = [
            ["name"=>"PROFESIONAL V RESPONSABLE DE LOGÍSTICA E INSUMOS"],
            ["name"=>"DISEÑADOR GRAFICO"],
            ["name"=>"PROFESIONAL EN COMUNICACIÓN"],
            ["name"=>"PROFESIONAL RESPONSABLE SOCIAL EMPRESARIAL"],
            ["name"=>"ASESOR DE COMUNICACIÓN"],
            ["name"=>"GERENTE DE PLANIFICACIÓN Y DESARROLLO"],
            ["name"=>"ASISTENTE ADMINISTRATIVO"],
            ["name"=>"RESPONSABLE DE PROYECTOS"],
            ["name"=>"PROFESIONAL EN PROYECTOS"],
            ["name"=>"TÉCNICO EN PROYECTOS II"],
            ["name"=>"PROFESIONAL EN CALCULO Y DISEÑO DE OBRAS CIVILES"],
            ["name"=>"PROFESIONAL EN INFRAESTRUCTURA"],
            ["name"=>"PROFESIONAL EN INSPECCIÓN DE OBRAS CIVILES"],
            ["name"=>"TÉCNICO EN GESTIÓN AMBIENTAL"],
            ["name"=>"RESPONSABLE DE NORMAS Y CALIDAD"],
            ["name"=>"RESPONSABLE DE CALIDAD Y NORMAS"],
            ["name"=>"RESPONSABLE DE PLANIFICACIÓN"],
            ["name"=>"PROFESIONAL EN PLANIFICACIÓN"],
            ["name"=>"RESPONSABLE DE SISTEMAS"],
            ["name"=>"ENCARGADO DE SEGURIDAD INFORMÁTICA"],
            ["name"=>"ENCARGADO DE SOPORTE TÉCNICO"],
            ["name"=>"TÉCNICO - SOPORTE"],
            ["name"=>"ENCARGADA DE DESARROLLO"],
            ["name"=>"PROFESIONAL DESARROLLADOR"],
            ["name"=>"TÉCNICO DESARROLLADOR II"],
            ["name"=>"TÉCNICO EN PROYECTOS I"],
            ["name"=>"TÉCNICO DESARROLLADOR I"],
            ["name"=>"GERENTE ADMINISTRATIVO FINANCIERO"],
            ["name"=>"ASISTENTE ADMINISTRATIVO"],
            ["name"=>"JEFE ADMINISTRATIVO"],
            ["name"=>"ENCARGADO DE SERVICIOS GENERALES"],
            ["name"=>"AUXILIAR SERVICIOS GENERALES"],
            ["name"=>"TÉCNICO FINANCIERO SERVICIOS GENERALES"],
            ["name"=>"ENCARGADO DE ACTIVOS FIJOS"],
            ["name"=>"TÉCNICO EN ALMACENES"],
            ["name"=>"TÉCNICO EN ACTIVO FIJOS"],
            ["name"=>"TÉCNICO ACTIVOS FIJOS LA PAZ"],
            ["name"=>"TÉCNICO EN ALMACENES I"],
            ["name"=>"RESPONSABLE TRIBUTARIO"],
            ["name"=>"AUXILIAR TRIBUTARIO I"],
            ["name"=>"ENCARGADO DE TRIBUTOS"],
            ["name"=>"TECNICO TRIBUTARIO"],
            ["name"=>"TECNICO EN ADUANAS"],
            ["name"=>"RESPONSABLE DE PRESUPUESTOS"],
            ["name"=>"ENCARGADO DE PRESUPUESTOS"],
            ["name"=>"RESPONSABLE DE TESORERÍA"],
            ["name"=>"ENCARGADO DE TESORERÍA"],
            ["name"=>"AUXILIAR FINANCIERA DISTRIBUCIÓN"],
            ["name"=>"TÉCNICO ADMINISTRATIVO FINANCIERO"],
            ["name"=>"JEFA FINANCIERA"],
            ["name"=>"APOYO RESPONSABLE DE CONTABILIDAD"],
            ["name"=>"AUXILIAR APOYO CONTABLE"],
            ["name"=>"AUXILIAR FINANCIERA GAF"],
            ["name"=>"RESPONSABLE DE CONTABILIDAD"],
            ["name"=>"AUXILIAR CONTABLE"],
            ["name"=>"RESPONSABLE DE RECURSOS HUMANOS"],
            ["name"=>"TÉCNICO EN RECURSOS HUMANOS I"],
            ["name"=>"TÉCNICO EN RECURSOS HUMANOS IV"],
            ["name"=>"AUX. ADMINISTRATIVO RECURSOS HUMANOS"],
            ["name"=>"TÉCNICO EN RECURSOS HUMANOS II"],
            ["name"=>"TÉCNICO EN RECURSOS HUMANOS III"],
            ["name"=>"TÉCNICO EN RECURSOS HUMANOS"],
            ["name"=>"JEFA DE CONTRATACIONES"],
            ["name"=>"TÉCNICO EN CONTRATACIONES VII"],
            ["name"=>"TÉCNICO EN CONTRATACIONES IV"],
            ["name"=>"TÉCNICO EN CONTRATACIONES II"],
            ["name"=>"TÉCNICO EN CONTRATACIONES III"],
            ["name"=>"AUXILIAR DE CONTRATACIONES"],
            ["name"=>"TECNICO DE CONTRATACIONES I"],
            ["name"=>"RESPONSABLE DE CONTRATACIONES"],
            ["name"=>"TECNICO EN COBRANZAS"],
            ["name"=>"RESPONSABLE DE IMPORTACIONES"],
            ["name"=>"AUXILIAR ARCHIVO CENTRAL LA PAZ"],
            ["name"=>"AUXILIAR VENTANILLA UNICA"],
            ["name"=>"MENSAJERIA"],
            ["name"=>"PROFESIONAL ANALISTA FINANCIERA"],
            ["name"=>"ANALISIS DE COSTO OPERATIVO"],
            ["name"=>"AUXILIAR ASISTENTE DE BIBLIOTECOLOGÍA"],
            ["name"=>"RESPONSABLE DE ARCHIVO"],
            ["name"=>"AUXILIAR DE ARCHIVO"],
            ["name"=>"AUXILIAR ADMINISTRATIVO"],
            ["name"=>"GERENTE DE PRODUCCIÓN LÁCTEOS"],
            ["name"=>"ASISTENTE ADMINISTRATIVO"],
            ["name"=>"JEFE DE GESTIÓN DE PRODUCCIÓN LÁCTEOS "],
            ["name"=>"JEFE DE PRODUCCIÓN LÁCTEOS"],
            ["name"=>"TÉCNICO PRODUCCIÓN LÁCTEOS "],
            ["name"=>"TÉCNICO EN APROVISIONAMIENTO"],
            ["name"=>"AUXILIAR I EN APROVISIONAMIENTO"],
            ["name"=>"JEFE DE MANTENIMIENTO "],
            ["name"=>"AUXILIAR DE MANTENIMIENTO II"],
            ["name"=>"PROFESIONAL EN GESTIÓN DE CALIDAD"],
            ["name"=>"TÉCNICO EN CALIDAD"],
            ["name"=>"TÉCNICO EN CALIDAD I"],
            ["name"=>"TÉCNICO SYSO Y MEDIO AMBIENTE"],
            ["name"=>"TÉCNICO EN CONTROL DE ALMACENES PRODUCTO TERMINADO"],
            ["name"=>"TÉCNICO EN MICROBIOLOGÍA"],
            ["name"=>"COORDINADOR GENERAL"],
            ["name"=>"JEFE DE SERVICIOS ALIMENTICIOS"],
            ["name"=>"AUXILIAR ADMINISTRATIVO"],
            ["name"=>"ABOGADA COORDINACIÓN GENERAL"],
            ["name"=>"RESPONSABLE ACE NACIONAL"],
            ["name"=>"ANALISTA FINANCIERA"],
            ["name"=>"ENCARGADO LEGAL DE ACE LA PAZ"],
            ["name"=>"SOPORTE ADMINISTRATIVO Y LOGÍSTICA"],
            ["name"=>"ENCARGADA DE LOGÍSTICA"],
            ["name"=>"RESPONSABLE DE PROCESOS DE GESTIÓN"],
            ["name"=>"TÉCNICO DEL ALIMENTO ESCOLAR LA PAZ - RACIÓN SÓLIDA"],
            ["name"=>"RESPONSABLE DEL ALIMENTO ESCOLAR LA PAZ"],
            ["name"=>"TÉCNICO NUTRICIONISTA DEL ALIMENTO ESCOLAR LA PAZ"],
            ["name"=>"TÉCNICO ADMINISTRATIVO FINANCIERO DEL ALIMENTO ESCOLAR LA PAZ"],
            ["name"=>"CHÓFER DEL ALIMENTO ESCOLAR LA PAZ"],
            ["name"=>"TÉCNICO DEL ALIMENTO ESCOLAR LA PAZ - RACIÓN LÍQUIDA"],
            ["name"=>"CHOFER DESAYUNO ESCOLAR EL ALTO"],
            ["name"=>"AUXILIAR DE ALMACÉN DEL ALIMENTO ESCOLAR LA PAZ"],
            ["name"=>"ASESORA LEGAL"],
            ["name"=>"ASISTENTE "],
            ["name"=>"RESPONSABLE DE CONTRATOS"],
            ["name"=>"ABOGADA "],
            ["name"=>"PROCURADOR "],
            ["name"=>"ABOGADO "],
            ["name"=>"JEFE DE AUDITORIA INTERNA"],
            ["name"=>"SUPERVISORA DE AUDITORIA INTERNA"],
            ["name"=>"AUDITOR INTERNO"],
            ["name"=>"AUXILIAR VII "],
            ["name"=>"AUDITORA INTERNO"],
            ["name"=>"GERENTE DE PRODUCCIÓN DE ENDULZANTES Y FRUTAS"],
            ["name"=>"AUXILIAR III - ADMINISTRATIVO"],
            ["name"=>"ENCARGADA COMERCIAL ENDULZANTES"],
            ["name"=>"APOYO ADMINISTRATIVO"],
            ["name"=>"ENCARGADA DE SEGUIMIENTO AL PROCESAMIENTO DE FRUTAS"],
            ["name"=>"SEGUIMIENTO Y CONTROL DE PRODUCCIÓN PRIMARIA"],
            ["name"=>"RESPONSABLE DE ESCUELA APÍCOLA Y DESARROLLO DE PRODUCTOS"],
            ["name"=>"RESPONSABLE DE SISTEMA DE GESTIÓN"],
            ["name"=>"TÉCNICO EN APOYO APÍCOLA EN ACOPIO Y PRODUCCIÓN"],
            ["name"=>"RESPONSABLE DE SEGUIMIENTO Y CONTROL DE PRODUCCIÓN PRIMARIA"],
            ["name"=>"RESPONSABLE DE SISTEMA DE INFORMACIÓN Y CONTROL DE CARTERA"],
            ["name"=>"RESPONSABLE DE SEGUIMIENTO Y MONITOREO"],
            ["name"=>"RESPONSABLE DE PROCESAMIENTO Y PRODUCCIÓN"],
            ["name"=>"ENCARGADO DE SEGUIMIENTO AL PROCESAMIENTO DE ENDULZANTES"],
            ["name"=>"AUXILIAR ADMINISTRATIVO I"],
            ["name"=>"GERENTE EJECUTIVO"],
            ["name"=>"SECRETARIA DE GERENCIA"],
            ["name"=>"AUXILIAR DE MENSAJERÍA"],
            ["name"=>"JEFE DE SEGURIDAD"],
            ["name"=>"CHOFER"],
            ["name"=>"GERENTE COMERCIAL"],
            ["name"=>"ASISTENTE GERENCIA COMERCIAL"],
            ["name"=>"RESPONSABLE DE COBRANZAS"],
            ["name"=>"ENCARGADO DE COBRANZAS"],
            ["name"=>"TÉCNICO ENCARGADO COBRANZAS"],
            ["name"=>"AUXILIAR IV DE COBRANZAS"],
            ["name"=>"TÉCNICO EN MARKETING Y DISEÑO"],
            ["name"=>"PROFESIONAL EN MARKETING"],
            ["name"=>"TÉCNICO V EN MARKETING Y DISEÑO"],
            ["name"=>"RESPONSABLE DE MERCADO EXTERNO"],
            ["name"=>"RESPONSABLE DE MERCADO INTERNO ABIERTO"],
            ["name"=>"ENCARGADO MERCADO INTERNO ABIERTO"],
            ["name"=>"ENCARGADO DE DISTRIBUCIÓN MERCADO INTERNO"],
            ["name"=>"OPERADOR DE ALMACÉN LACTEOS Y FRUTÍCOLAS"],
            ["name"=>"TÉCNICO EN DISTRIBUCIÓN "],
            ["name"=>"TÉCNICO EN REPOSICIÓN PUNTOS DE VENTA EXTERNOS"],
            ["name"=>"OPERADOR DE ALMACÉN AMAZÓNICOS Y ENDULZANTES"],
            ["name"=>"TÉCNICO EN MERCADO INTERNO"],
            ["name"=>"ASISTENTE SUPERVISORA RUTEO -1 DISTRIBUIDORA VILLA FÁTIMA"],
            ["name"=>"VENDEDOR TELEFÉRICO LÍNEA ROJA"],
            ["name"=>"CHOFER"],
            ["name"=>"CHOFER MERCADO INTERNO II"],
            ["name"=>"REPONEDOR SUPERMERCADO"],
            ["name"=>"AUXILIAR VENDEDORA"],
        ];

        foreach ($positions as $position) {
            App\Position::create($position);
        }
    }
}
